CREATE TABLE IF NOT EXISTS interest_area (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sido TEXT NOT NULL,
    sigungu TEXT NOT NULL,
    dong TEXT,
    memo TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS apartment_complex (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sido TEXT,
    sigungu TEXT,
    dong TEXT,
    address TEXT,
    build_year BIGINT,
    household_count BIGINT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    complex_grade TEXT,
    memo TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS manual_listing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complex_id BIGINT NOT NULL,
    area_m2 DOUBLE PRECISION NOT NULL,
    sale_price BIGINT NOT NULL,
    expected_jeonse_price BIGINT,
    investment_type TEXT,
    takeover_jeonse_deposit BIGINT,
    rent_deposit BIGINT,
    expected_monthly_rent BIGINT,
    floor TEXT,
    direction TEXT,
    condition_memo TEXT,
    source_memo TEXT,
    checked_at TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (complex_id) REFERENCES apartment_complex(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sale_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complex_id BIGINT,
    complex_name TEXT,
    area_m2 DOUBLE PRECISION,
    deal_year BIGINT,
    deal_month BIGINT,
    deal_day BIGINT,
    price BIGINT,
    floor BIGINT,
    raw_address TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS rent_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complex_id BIGINT,
    complex_name TEXT,
    area_m2 DOUBLE PRECISION,
    deal_year BIGINT,
    deal_month BIGINT,
    deal_day BIGINT,
    deposit BIGINT,
    monthly_rent BIGINT,
    floor BIGINT,
    raw_address TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS user_finance_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_amount BIGINT NOT NULL,
    annual_income BIGINT,
    existing_debt BIGINT DEFAULT 0,
    interest_rate DOUBLE PRECISION,
    ltv_limit DOUBLE PRECISION,
    dsr_limit DOUBLE PRECISION,
    home_count BIGINT DEFAULT 0,
    owned_real_estate_value BIGINT DEFAULT 0,
    owned_real_estate_debt BIGINT DEFAULT 0,
    credit_loan_balance BIGINT DEFAULT 0,
    other_loan_balance BIGINT DEFAULT 0,
    use_manual_ltv BIGINT DEFAULT 0,
    manual_ltv_rate DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    finance_profile_id BIGINT,
    required_cash BIGINT,
    shortage_cash BIGINT,
    jeonse_ratio DOUBLE PRECISION,
    discount_vs_recent_avg DOUBLE PRECISION,
    drop_from_high DOUBLE PRECISION,
    bargain_score BIGINT,
    undervalue_score BIGINT,
    risk_score BIGINT,
    investment_type TEXT,
    current_required_cash BIGINT,
    future_required_cash BIGINT,
    monthly_cash_flow BIGINT,
    acquisition_tax BIGINT,
    local_education_tax BIGINT,
    brokerage_fee BIGINT,
    legal_fee BIGINT,
    reserve_cost BIGINT,
    total_transaction_cost BIGINT,
    applied_tax_rule_version TEXT,
    applied_brokerage_rule_version TEXT,
    liquidity_score BIGINT,
    investment_score BIGINT,
    complex_grade TEXT,
    sale_price_snapshot BIGINT,
    jeonse_price_snapshot BIGINT,
    area_m2_snapshot DOUBLE PRECISION,
    complex_name_snapshot TEXT,
    available_cash_snapshot BIGINT,
    annual_income_snapshot BIGINT,
    buyer_type_snapshot TEXT,
    expected_loan_amount BIGINT,
    monthly_repayment BIGINT,
    loan_rule_version TEXT,
    decision TEXT,
    summary TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (listing_id) REFERENCES manual_listing(id) ON DELETE CASCADE,
    FOREIGN KEY (finance_profile_id) REFERENCES user_finance_profile(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complex_id BIGINT,
    listing_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (complex_id) REFERENCES apartment_complex(id) ON DELETE CASCADE,
    FOREIGN KEY (listing_id) REFERENCES manual_listing(id) ON DELETE CASCADE,
    CHECK (complex_id IS NOT NULL OR listing_id IS NOT NULL),
    UNIQUE (complex_id, listing_id)
);

CREATE TABLE IF NOT EXISTS policy_import (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_text TEXT NOT NULL,
    source_name TEXT,
    target_rule_type TEXT NOT NULL,
    effective_date TEXT,
    parser_name TEXT NOT NULL,
    parser_status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS rule_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_import_id BIGINT NOT NULL,
    target_rule_type TEXT NOT NULL,
    rule_name TEXT NOT NULL,
    rule_version TEXT,
    previous_rule_json TEXT,
    proposed_rule_json TEXT NOT NULL,
    changed_fields_json TEXT,
    confidence DOUBLE PRECISION,
    warnings TEXT,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    reviewed_at TIMESTAMPTZ,
    applied_at TIMESTAMPTZ,
    FOREIGN KEY (policy_import_id) REFERENCES policy_import(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS region_policy_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_level TEXT NOT NULL,
    sido TEXT NOT NULL,
    sigungu TEXT,
    dong TEXT,
    policy_type TEXT NOT NULL,
    effective_from TEXT NOT NULL,
    effective_to TEXT,
    notes TEXT,
    source_policy_import_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (source_policy_import_id) REFERENCES policy_import(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS policy_event (
    policy_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_type TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    detail TEXT NOT NULL,
    effective_from TEXT NOT NULL,
    effective_to TEXT,
    affected_region_sido TEXT,
    affected_region_sigungu TEXT,
    affected_region_dong TEXT,
    affected_buyer_type TEXT NOT NULL,
    affected_investment_purpose TEXT NOT NULL,
    impact_level TEXT NOT NULL,
    calculation_supported BIGINT NOT NULL,
    action_required BIGINT NOT NULL,
    source_text TEXT NOT NULL,
    source_name TEXT,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS policy_event_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_import_id BIGINT NOT NULL,
    policy_type TEXT NOT NULL,
    title TEXT NOT NULL,
    impact_level TEXT NOT NULL,
    proposed_event_json TEXT NOT NULL,
    confidence DOUBLE PRECISION,
    warnings TEXT,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    reviewed_at TIMESTAMPTZ,
    applied_at TIMESTAMPTZ,
    FOREIGN KEY (policy_import_id) REFERENCES policy_import(id) ON DELETE CASCADE
);
